// Barrel over api/: the request client plus one module per API area. Importers
// keep using '@/lib/api' (or './api') for every type and function.
export * from './api/client'
export * from './api/nodes'
export * from './api/usage'
export * from './api/users'
export * from './api/credentials'
export * from './api/groups'
export * from './api/groupBackends'
export * from './api/joinRequests'
export * from './api/metadata'
export * from './api/profileValidation'
export * from './api/search'
export * from './api/connectors'
export * from './api/staging'
export * from './api/storageRouting'
export * from './api/blobs'
export * from './api/sync'
export * from './api/notifications'
export * from './api/onboarding'
export * from './api/devices'
export * from './api/sessions'
export * from './api/assistant'
export * from './api/placement'
