import { readonly } from 'vue'
import {
  createGroupBackend,
  disableGroupBackend,
  enableGroupBackend,
  listGroupBackends,
  replaceBackendCredentials,
  replaceGroupBackend,
} from './aruna/backends'
import {
  listCatalogPage,
  listGroupMetadata,
  listRecentMetadata,
  loadMetadata,
  metadataAtPath,
  refreshProfiles,
} from './aruna/catalog'
import {
  checkConnectorConfig,
  checkGroupConnector,
  createGroupConnector,
  deleteGroupConnector,
  getGroupConnector,
  listConnectorEntries,
  listGroupConnectors,
  replaceGroupConnector,
} from './aruna/connectors'
import {
  fetchRoCrateRaw,
  invalidateCrate,
  loadProfileCrate,
  loadRoCrate,
} from './aruna/crates'
import {
  createMetadata,
  deleteMetadataDocument,
  getMetadataDocument,
  getMetadataItem,
  replaceMetadataRoCrate,
} from './aruna/documents'
import {
  addGroupMember,
  createGroup,
  createGroupRole,
  deleteGroupRole,
  discoverableGroups,
  getGroup,
  getGroupUsage,
  getGroupUsageHistory,
  groups,
  leaveGroup,
  listGroupMembers,
  myGroups,
  removeGroupMember,
} from './aruna/groups'
import {
  canInspectUsers,
  canManageOnboarding,
  canManageQuarantine,
  canWithdrawPids,
  currentUser,
  isRealmAdmin,
} from './aruna/identity'
import { mapMetadataDoc, metadata, profiles } from './aruna/mapping'
import { isManagementNode, loadInfo, nodes, realm, setRealmQuota } from './aruna/realm'
import {
  searchBuckets,
  searchMetadata,
  searchObjects,
  searchUnified,
  runSparql,
} from './aruna/search'
import { refresh, setApiBaseUrl, setAuthToken } from './aruna/session'
import {
  createStagingJob,
  getStagingJob,
  listStagingJobs,
  listStagingReferences,
  stageBatch,
  stageBlob,
} from './aruna/staging'
import {
  apiBaseUrl,
  apiGroups,
  authError,
  authRejected,
  authToken,
  bootstrapped,
  cratePending,
  credentials,
  error,
  fullCrates,
  loading,
  metadataItems,
  nodeInfo,
  profileCrateParses,
  profileItems,
  profileValidationCapabilities,
  profileValidationStatuses,
  realmInfo,
  saving,
  sessionEpoch,
  usageInfo,
  userInfo,
} from './aruna/state'
import {
  getBlobLocations,
  getBucketRouting,
  getGroupRouting,
  putBucketRouting,
  putGroupRouting,
  replicateBlob,
} from './aruna/storage'
import {
  createSyncRelationship,
  deleteSyncRelationship,
  getSyncRelationship,
  listSyncRelationships,
  runSyncRelationship,
  updateSyncReferenceHandling,
} from './aruna/sync'
import {
  createS3Credentials,
  getUser,
  listUsers,
  resolveUsers,
  revokeS3Credential,
  searchUsers,
  toggleFavourite,
  updateUserProfile,
} from './aruna/users'
import {
  loadProfileValidationCapabilities,
  loadProfileValidationStatus,
  revalidateProfileValidationStatus,
} from './aruna/validation'

export { readableIri } from '@/lib/identifiers'
export { colorFor, initials } from './aruna/format'
export { publicProfileIri, profileReferenceIri } from './aruna/profileIri'
export { isRecencyOrdered, walkRecentPages, type RecentWalk } from './aruna/catalog'
export { isUnsupportedEndpoint } from './aruna/connectors'
export { CrateNotReadyError } from './aruna/crates'
export {
  profileRulesLoadState,
  profileValidationPresentation,
  serverValidationRequiredConstraints,
  type ProfileRulesLoadState,
  type ProfileValidationPresentation,
  type ProfileValidationPresentationStatus,
} from './aruna/validation'
export {
  buildObjectSearchExportArtifact,
  buildSparqlExportArtifact,
  sparqlCoverageStatus,
  DEFAULT_SPARQL_MODE,
  IncompleteSparqlResultError,
} from './aruna/search'

export function useAruna() {
  return {
    apiBaseUrl,
    authToken,
    loading,
    saving,
    error,
    authError,
    authRejected: readonly(authRejected),
    bootstrapped,
    sessionEpoch: readonly(sessionEpoch),
    nodeInfo,
    realmInfo,
    usageInfo,
    userInfo,
    apiGroups,
    credentials,
    realm,
    currentUser,
    isRealmAdmin,
    canInspectUsers,
    canManageOnboarding,
    canManageQuarantine,
    canWithdrawPids,
    isManagementNode,
    nodes,
    groups,
    myGroups,
    discoverableGroups,
    metadata,
    profiles,
    metadataItems,
    profileItems,
    fullCrates,
    profileCrateParses: readonly(profileCrateParses),
    cratePending,
    profileValidationStatuses: readonly(profileValidationStatuses),
    profileValidationCapabilities: readonly(profileValidationCapabilities),
    refresh,
    loadInfo,
    loadMetadata,
    refreshProfiles,
    toMetadataDoc: mapMetadataDoc,
    loadRoCrate,
    loadProfileCrate,
    loadProfileValidationCapabilities,
    loadProfileValidationStatus,
    revalidateProfileValidationStatus,
    createMetadata,
    getMetadataDocument,
    getMetadataItem,
    metadataAtPath,
    fetchRoCrateRaw,
    invalidateCrate,
    replaceMetadataRoCrate,
    deleteMetadataDocument,
    listCatalogPage,
    listGroupMetadata,
    listRecentMetadata,
    toggleFavourite,
    updateUserProfile,
    setRealmQuota,
    createGroup,
    getGroup,
    getGroupUsage,
    getGroupUsageHistory,
    createS3Credentials,
    listGroupConnectors,
    getGroupConnector,
    createGroupConnector,
    replaceGroupConnector,
    deleteGroupConnector,
    checkConnectorConfig,
    checkGroupConnector,
    listConnectorEntries,
    listGroupBackends,
    createGroupBackend,
    replaceGroupBackend,
    disableGroupBackend,
    enableGroupBackend,
    replaceBackendCredentials,
    getGroupRouting,
    putGroupRouting,
    getBucketRouting,
    putBucketRouting,
    getBlobLocations,
    replicateBlob,
    stageBlob,
    stageBatch,
    listStagingJobs,
    createStagingJob,
    getStagingJob,
    listStagingReferences,
    revokeS3Credential,
    listGroupMembers,
    addGroupMember,
    removeGroupMember,
    leaveGroup,
    createGroupRole,
    deleteGroupRole,
    searchUsers,
    getUser,
    resolveUsers,
    listUsers,
    runSparql,
    searchMetadata,
    searchUnified,
    searchObjects,
    searchBuckets,
    listSyncRelationships,
    getSyncRelationship,
    createSyncRelationship,
    runSyncRelationship,
    updateSyncReferenceHandling,
    deleteSyncRelationship,
    setAuthToken,
    setApiBaseUrl,
  }
}
