// Bundled ontology vocabulary for the profile builder's autocomplete: the
// schema.org core release (CC BY-SA 3.0, https://schema.org/docs/terms.html)
// plus the DCMI Metadata Terms (CC BY 4.0). vocab.json is generated by
// scripts/build-vocab.mjs from the official releases; no GPL-licensed sources.
// Loaded lazily (dynamic import) so the ~520 KB data lands in its own async
// chunk, fetched only when a picker actually needs suggestions.
import { normalizeTypeUri, SCHEMA_ORG } from './uri'
import type { ProfileValueKind } from './types'

export interface VocabTerm {
  uri: string
  name: string
  label: string
  description: string
  source: string
  // Present on properties only: a suggested value kind derived from the term's
  // range, the range itself, and the types the term may be used on.
  kind?: string
  targets?: string[]
  domains?: string[]
  // Present on classes only: the direct superclasses.
  parents?: string[]
}

export interface VocabData {
  properties: VocabTerm[]
  classes: VocabTerm[]
}

let vocabPromise: Promise<VocabData> | null = null

export function loadVocabulary(): Promise<VocabData> {
  vocabPromise ??= import('./vocab.json').then((module) => module.default as VocabData)
  return vocabPromise
}

// schema.org's primitive ranges. They are not classes, so a range naming one
// offers a typed value input rather than a reference to another entity.
const DATATYPE_KINDS: Readonly<Record<string, ProfileValueKind>> = {
  Text: 'text',
  Number: 'number',
  Integer: 'integer',
  Float: 'number',
  Boolean: 'boolean',
  Date: 'date',
  DateTime: 'datetime',
  Time: 'text',
  URL: 'url',
}

export function datatypeKind(uri: string): ProfileValueKind | undefined {
  return uri.startsWith(SCHEMA_ORG) ? DATATYPE_KINDS[uri.slice(SCHEMA_ORG.length)] : undefined
}

// Properties every entity may carry, whatever its type says.
const UNIVERSAL_PROPERTIES: ReadonlySet<string> =
  new Set(['name', 'description', 'identifier', 'url'].map((name) => `${SCHEMA_ORG}${name}`))

export interface VocabIndex {
  properties: VocabTerm[]
  classes: VocabTerm[]
  property(uri: string): VocabTerm | undefined
  /** A property by its crate key ("author", "abstract"), schema.org first. */
  propertyNamed(name: string): VocabTerm | undefined
  class(uri: string): VocabTerm | undefined
  /** The type itself plus every superclass, nearest first. */
  classAncestors(uri: string): string[]
  /** The type itself plus every subclass. */
  classDescendants(uri: string): string[]
  /** Properties whose domain names one of `types` or an ancestor of it. */
  propertiesForTypes(types: string[]): VocabTerm[]
  /** The classes a reference to a property with this range may point at. */
  classesInRange(targets: string[] | undefined): VocabTerm[]
  searchClasses(query: string, limit?: number): VocabTerm[]
  searchProperties(query: string, types?: string[], limit?: number): VocabTerm[]
}

const indexes = new WeakMap<VocabData, VocabIndex>()

export function vocabIndex(data: VocabData): VocabIndex {
  const existing = indexes.get(data)
  if (existing) return existing
  const built = buildIndex(data)
  indexes.set(data, built)
  return built
}

export function loadVocabIndex(): Promise<VocabIndex> {
  return loadVocabulary().then(vocabIndex)
}

function buildIndex(data: VocabData): VocabIndex {
  const propertyByUri = new Map(data.properties.map((term) => [term.uri, term]))
  const propertyByName = new Map<string, VocabTerm>()
  for (const term of data.properties) if (!propertyByName.has(term.name)) propertyByName.set(term.name, term)
  const classByUri = new Map(data.classes.map((term) => [term.uri, term]))
  const children = new Map<string, string[]>()
  for (const term of data.classes) {
    for (const parent of term.parents ?? []) children.set(parent, [...(children.get(parent) ?? []), term.uri])
  }
  const ancestorCache = new Map<string, string[]>()
  const descendantCache = new Map<string, string[]>()

  const classAncestors = (uri: string): string[] => {
    const start = normalizeTypeUri(uri)
    const cached = ancestorCache.get(start)
    if (cached) return cached
    const seen = [start]
    const visited = new Set(seen)
    for (let cursor = 0; cursor < seen.length; cursor += 1) {
      for (const parent of classByUri.get(seen[cursor])?.parents ?? []) {
        if (visited.has(parent)) continue
        visited.add(parent)
        seen.push(parent)
      }
    }
    ancestorCache.set(start, seen)
    return seen
  }

  const classDescendants = (uri: string): string[] => {
    const start = normalizeTypeUri(uri)
    const cached = descendantCache.get(start)
    if (cached) return cached
    const seen = [start]
    const visited = new Set(seen)
    for (let cursor = 0; cursor < seen.length; cursor += 1) {
      for (const child of children.get(seen[cursor]) ?? []) {
        if (visited.has(child)) continue
        visited.add(child)
        seen.push(child)
      }
    }
    descendantCache.set(start, seen)
    return seen
  }

  const propertiesForTypes = (types: string[]): VocabTerm[] => {
    const domains = new Set(types.flatMap(classAncestors))
    const matched = data.properties.filter((term) =>
      UNIVERSAL_PROPERTIES.has(term.uri) || term.domains?.some((domain) => domains.has(domain)))
    return matched.sort((a, b) => a.name.localeCompare(b.name, 'en'))
  }

  const rangeCache = new Map<string, VocabTerm[]>()
  const classesInRange = (targets: string[] | undefined): VocabTerm[] => {
    const key = (targets ?? []).join(' ')
    const cached = rangeCache.get(key)
    if (cached) return cached
    const uris = new Set((targets ?? []).flatMap(classDescendants))
    const matched = key ? data.classes.filter((term) => uris.has(term.uri)) : []
    rangeCache.set(key, matched)
    return matched
  }

  const searchProperties = (query: string, types?: string[], limit = 20): VocabTerm[] => {
    const suggested = types?.length ? new Set(propertiesForTypes(types).map((term) => term.uri)) : null
    return rank(data.properties, query, limit, (term) => (suggested?.has(term.uri) ? -0.5 : 0))
  }

  return {
    properties: data.properties,
    classes: data.classes,
    property: (uri) => propertyByUri.get(normalizeTypeUri(uri)),
    propertyNamed: (name) => propertyByName.get(name),
    class: (uri) => classByUri.get(normalizeTypeUri(uri)),
    classAncestors,
    classDescendants,
    propertiesForTypes,
    classesInRange,
    searchClasses: (query, limit = 20) => rank(data.classes, query, limit),
    searchProperties,
  }
}

// Exact name, then prefix, then substring, then a description hit; `bonus`
// lets a caller float the terms that suit the entity at hand.
function rank(
  terms: VocabTerm[],
  query: string,
  limit: number,
  bonus: (term: VocabTerm) => number = () => 0,
): VocabTerm[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const scored: Array<{ term: VocabTerm; score: number }> = []
  for (const term of terms) {
    const name = term.name.toLowerCase()
    const label = term.label.toLowerCase()
    let score = -1
    if (name === q || label === q) score = 0
    else if (name.startsWith(q) || label.startsWith(q)) score = 1
    else if (name.includes(q) || label.includes(q)) score = 2
    else if (term.description.toLowerCase().includes(q)) score = 3
    if (score >= 0) scored.push({ term, score: score + bonus(term) })
  }
  scored.sort((a, b) => a.score - b.score || a.term.name.localeCompare(b.term.name, 'en'))
  return scored.slice(0, limit).map((entry) => entry.term)
}

// The generator's kind strings map 1:1 onto ProfileValueKind scalars; keep the
// mapping explicit so an unexpected value degrades to undefined, not a crash.
const KINDS: ReadonlySet<string> = new Set([
  'text',
  'longtext',
  'integer',
  'number',
  'boolean',
  'date',
  'datetime',
  'url',
  'email',
  'entity',
])

export function vocabKind(term: VocabTerm): ProfileValueKind | undefined {
  return term.kind && KINDS.has(term.kind) ? (term.kind as ProfileValueKind) : undefined
}

// Ranked substring search over name/label/description. Exact name/label matches
// first, then prefix matches, then substring, then description hits.
export function searchVocabTerms(terms: VocabTerm[], query: string, limit = 8): VocabTerm[] {
  return rank(terms, query, limit)
}

// Short source tag for display ("schema.org" / "dcterms").
export function vocabSourceLabel(term: VocabTerm): string {
  return term.source === 'dcterms' ? 'Dublin Core' : term.source
}
